bin = [
  { name = "main", path = "src/main.rs" },
  { name = "2025_day_1", path = "src/2025/day_1.rs" },
  { name = "2025_day_2", path = "src/2025/day_2.rs" },
  { name = "2025_day_3", path = "src/2025/day_3.rs" },
  { name = "2025_day_4", path = "src/2025/day_4.rs" },
  { name = "2025_day_5", path = "src/2025/day_5.rs" },
  { name = "2025_day_6", path = "src/2025/day_6.rs" },
  { name = "2025_day_7", path = "src/2025/day_7.rs" },
  { name = "2025_day_8", path = "src/2025/day_8.rs" },
  { name = "2025_day_9", path = "src/2025/day_9.rs" },
  { name = "2025_day_10", path = "src/2025/day_10.rs" },

  { name = "day_1", path = "src/2024/day_1.rs" },
  { name = "day_2", path = "src/2024/day_2.rs" },
  { name = "day_3", path = "src/2024/day_3.rs" },
  { name = "day_4", path = "src/2024/day_4.rs" },
  { name = "day_5", path = "src/2024/day_5.rs" },
  { name = "day_6", path = "src/2024/day_6.rs" },
  { name = "day_7", path = "src/2024/day_7.rs" },
  { name = "day_8", path = "src/2024/day_8.rs" },
  { name = "day_9", path = "src/2024/day_9.rs" },
  { name = "day_10", path = "src/2024/day_10.rs" },
  { name = "day_11", path = "src/2024/day_11.rs" },
  { name = "day_12", path = "src/2024/day_12.rs" },
  { name = "day_13", path = "src/2024/day_13.rs" },
  { name = "day_14", path = "src/2024/day_14.rs" },
  { name = "day_15", path = "src/2024/day_15.rs" },
  { name = "day_16", path = "src/2024/day_16.rs" },
  { name = "day_17", path = "src/2024/day_17.rs" },
  { name = "day_18", path = "src/2024/day_18.rs" },
  { name = "day_19", path = "src/2024/day_19.rs" },
  { name = "day_20", path = "src/2024/day_20.rs" },
  { name = "day_21", path = "src/2024/day_21.rs" },
  { name = "day_22", path = "src/2024/day_22.rs" },
  { name = "day_23", path = "src/2024/day_23.rs" },
]

[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
regex = "1.12.4"
